services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    ports:
      - 13000:3000
  db:
    image: mysql:8.4
    ports:
      - 13306:3306
    volumes:
      - db-data:/var/lib/mysql
      - ./scripts/initdb.d:/docker-entrypoint-initdb.d
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dating
volumes:
  db-data: